# Site settings
title: "Phú Quốc Đảo"
url-title: "Điểm hẹn Phú Quốc"
description: "Phú Quốc và nơi hẹn hò"
paginate: 100
url: "https://site-mau-1.netlify.com"
permalink: /:year/:month/:title/
future: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_words: 25

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
  deploy_style: compressed

gems: [jekyll-paginate]
